[package]
name = "tauri-stretch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tauri.workspace = true
serde.workspace = true
serde_json.workspace = true
