[[hooks]]
stage = "build"
command = "cargo"
command_arguments = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false
